### PR TITLE
Add shebang to examples

### PR DESCRIPTION
**Pull request by frafra**

### CODE REVIEW

**Comment by bmuller** [comment]
Hey @frafra - these files are not set as executable (mode 644), so adding the hashbang won't make them executable.  I think it would either make sense to keep them as python files (.py, and run as `python filename.py`) or make them executable by changing the file mode and removing the `.py` if the hashbang is added.

**Review by bmuller — CHANGES_REQUESTED** [review]
Hey @frafra - these files are not set as executable (mode 644), so adding the hashbang won't make them executable.  I think it would either make sense to keep them as python files (.py, and run as `python filename.py`) or make them executable by changing the file mode and removing the `.py` if the hashbang is added.

**Comment by frafra** [comment]
Hey @bmuller, thank you for your reply.
I made them executable, but I am not sure on renaming them; it is still valid to keep the extension, as some editors rely on file extensions, but if you are sure about that I can drop it.

**Comment by bmuller** [comment]
Hey @frafra, I've thought about this some more, and I think the best thing to do would be to leave these as `.py` files that are not executable (and thus no hashbang).  The files exist to provide _Python_ examples of how to write code that uses the lib, not to act as utilities (executable bins) that people should run to do things.  They're just example Python files, and, as such, I think should remain as is.

I'm going to close the PR, but please feel free to comment if you have a different view.  I'm open to being convinced otherwise.  And thanks for the contribution!

**Comment by frafra** [comment]
No problem, it is a respectable opinion :-) It is your project after all :-)

**Pull request closed without merging**
