### PR TITLE
storage: fix to allow all values in storage

### PR DESCRIPTION
**Pull request by Tha-Robert**
Also fixes race condtion in get where we chech if it exits and
maybe cull value before we return it.

Signed-off-by: Robert Marklund robert.marklund@ericsson.com

### CODE REVIEW

**Comment by bmuller** [comment]
Hey @Tha-Robert - I see that this would allow the storage of a null (`None`) value, but why is this desired?  I could perhaps see if this was an attempt to create a `delete` function - but that would be another discussion.

**Comment by Tha-Robert** [comment]
For our purposes we need it for lazy delete functionality, not needed but preferred.
 
Second I dislike having values in storage that can have too meanings the actual value and no value exists. It takes a way one value that cant be stored in the storage. This ways its gets more generic, and fail proof.

//R

**Comment by bmuller** [comment]
Deleting a key/value and storing a null value are not the same thing, so this wouldn't get you the ability to delete.  For the second case, it could be solved by not doing anything if someone attempts to set a key/value where the value is `None`, which would mean that a `None` result from a get means only one thing - that the key doesn't exist.  If I made that change instead, the API wouldn't need to change.  What do you think about that solution?

**Comment by bmuller** [comment]
Closed from inactivity. Please feel free to reopen if you still see a need and want to discuss. Thanks!

**Pull request closed without merging**
