### PR TITLE
 unittests passing with python 2 and 3 und support universal wheel

### PR DESCRIPTION
**Pull request by F483**

### CODE REVIEW

**Comment by F483** [comment]
Note that the stand alone server still fails `twistd -noy examples/server.tac` so python 3 support cannot be claimed just yet.

**Comment by F483** [comment]
I'm not to familiar with the project code or twisted, it would be nice if someone cold look at why `python3 examples/server.tac` just exists instead of running the server.

**Comment by F483** [comment]
I am now very confidant that the all the code is ported to python3. All tests, examples and additional tests work as before in python 2 and 3.

Some tests conflict each other but work by themselves, so I need to figure out what is wrong there (help greatly appreciated, I'm not to familiar with twisted). The rpcudp dependencie needs to be updated first as well, or none of the travis tests will pass.

Some cruft also needs to be removed.

**Comment by F483** [comment]
@bmuller can you take a look at the status of my python 3 port, [all tests seem to pass fine on travis](https://travis-ci.org/bmuller/kademlia/builds/100613915)

I added a swarm test in an attempt to get more coverage, but it does not seem to work for some reason. It would be great if you have the time to take a [look at it](https://github.com/F483/kademlia/blob/master/kademlia/tests/test_swarm.py).

**Comment by bmuller** [comment]
Hey @F483 - first, I really appreciate all the help!  There are a few things in the PR, though, that don't seem necessary, like adding a new dependency on ipython and pubd, tons of new boilerplate in .gitignore, adding a dependency on the `six` package when all that's being used is a constant (that's just the same as `sys.version_info[0] == 2`) and a one line function.  Don't want to be pedantic - but I'd prefer to keep additional requirements to a minimum.  I think if those things are cleaned up a bit, should be ready for merging.

Thanks!

**Comment by F483** [comment]
ipython and pudb are not part of the package dependencies, they are only explicitly installed for development via the Makefile

I also use six to ensure correct types [here](https://github.com/F483/kademlia/blob/master/kademlia/network.py#L212) and it should likely also be used in other paces for better type control. I still have to look through the code and confirm the type correctness of python 2 vs python 3.

I wouldn't merge it until its resolved why the swarm test does not work and node compatibility between 2 and 3 has been verified.

**Comment by bmuller** [comment]
@F483 you added a file named `develop_requirements.txt` that lists packages that are not actual development requirements.  I'd prefer to not add unnecessary files and references (in the Makefile) to your personal development environment.  Please remove these personal items.  To be clear, I'd like to not have to go back and forth on this - it's a hard requirement for acceptance.

Your use of `six.b` is the one line function I was referring to.  I'd prefer to not add a dependency on the `six` package if all that's being used is a constant and a one line function.

**Comment by F483** [comment]
@bmuller I removed the dependencies as requested.

**Comment by bmuller** [comment]
Thanks!  So I took a look at your swarm test, and the first issue I can see is that in many places the asynchronous nature of some calls isn't accounted for.  So, for instance, [in the `setUp` method](https://github.com/F483/kademlia/blob/master/kademlia/tests/test_swarm.py#L38) the `bootstap` call will return immediately with a [Deferred](https://twistedmatrix.com/documents/current/api/twisted.internet.defer.Deferred.html) - the equivalent of a promise or future.  I see that you're sleeping to account for the time taken to actually bootstrap, but for these you should just yield the deferred and use the `twisted.internet.defer.inlineCallbacks` decorator (examples can be found [here](https://github.com/bmuller/twistar/blob/master/twistar/tests/test_transactions.py)).  The reasons for this are a bit complicated, but basically, "If your tests call a function which returns a Deferred, your test should return a Deferred" ([reasoning here](http://twistedmatrix.com/documents/current/core/howto/testing.html#leave-the-reactor-as-you-found-it)).  Let me know if you'd like to take a stab at it, and, if not, then I can try to fix it up a bit (though it might take a little while for me to get to it).

Thanks again for the help!

**Comment by bmuller** [comment]
Closed from inactivity. Please feel free to reopen if you still see a need and want to discuss - but I think many of these changes have been integrated by this point. Thanks!

**Pull request closed without merging**
